name: norka
version: git
title: Norka
icon: data/norka.png
summary: Text editor baked for simplicity.
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

base: core18

parts:
  norka:
    parse-info: [data/com.github.tenderowl.norka.appdata.xml]
    plugin: python
    source: .
    stage-packages:
      - python3
      - python3-gi
      - gir1.2-gtk-3.0
      - gir1.2-appindicator3-0.1
      - gir1.2-gee-0.8
    after:
      - granite
  granite:
    plugin: meson
    source: https://github.com/elementary/granite/archive/5.4.0.tar.gz
    source-type: tar
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - build-essential
      - libgee-0.8-dev
      - libgirepository1.0-dev
      - libgtk-3-dev
      - cmake
      - gobject-introspection
      - valac

apps:
  norka:
    command: bin/norka
    extensions: [gnome-3-28]
    plugs:
      - desktop
      - gsettings
      - wayland
      - x11
      - home
    common-id: com.github.tenderowl.norka