name: CI

# This workflow will run for any pull request or pushed commit
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        apt update
        apt install -y meson libgtksourceview-4-dev libwebkit2gtk-4.0-dev libgspell-1-dev meson gir1.2-gspell-1 gir1.2-gtksource-4 gir1.2-webkit2-4.0
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  # This workflow contains a single job called "flatpak"
  flatpak:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This job runs in a special container designed for building Flatpaks for AppCenter
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:6
      options: --privileged

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2
    
    # Builds your flatpak manifest using the Flatpak Builder action
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        # This is the name of the Bundle file we're building and can be anything you like
        bundle: Norka.flatpak
        # This uses your app's RDNN ID
        manifest-path: flatpak/com.github.tenderowl.norka.json

        # You can automatically run any of the tests you've created as part of this workflow
        run-tests: true

        # These lines specify the location of the elementary Runtime and Sdk
        repository-name: appcenter
        repository-url: https://flatpak.elementary.io/repo.flatpakrepo
        cache-key: "flatpak-builder-${{ github.sha }}"
        
